greenbone/gvm-tools

- README.rst
I made the requirements clearer by mentioning them before the installation
instructions and added a reference to the Python 3 dependency.
> Documentation

- gmp/gmp.py
- gmp/gvm_connection.py
Parameters hosts and ifaces were added to the GMP functions
create_user and modify_user to allow setting these properties of
the user.
> Add hosts and ifaces for get_user / modify_user

- scripts/application-detection.gmp
- scripts/clean-slave.gmp
- scripts/create-dummy-data.gmp
- scripts/nvt-scan.gmp
- scripts/startNVTScan.gmp
This commit makes the modified files compliant with the PEP 8 Style Guide
for Python code.
> Make GMP scripts PEP 8-compliant

- README.rst
* README.rst: Add subsection where to find more examples.
> Leave note in README about scripts folder.

- scripts/send_delta_emails.gmp
Retrieves all tasks where a particular tag is attached, creates a csv report and emails the results.
> .gmp script to create delta reports from previous tasks

- gmp/gmp.py
- gmp/gvm_connection.py
PLEASE CHECK if fix is correct (especially the format strings looked like there were some variables unused on purpose - but no comment)
> Fix all pylint errors in gmp.py and gvm_connection.py

- .gitignore
- gmp/gvm_connection.py
A try to fix issue https://github.com/greenbone/gvm-tools/issues/24
I don't know if this helps out, or not.
This is my first try at a pull request..
If it's messy and you hate it, I can always take it as a learning experience :)
--
Regards Falk
> A try to fix huge_tree for lxml for issue #24

- scripts/gen-random-targets.gmp
- scripts/monthly-report.gmp
- scripts/monthly-report2.gmp
- scripts/send-schedules.gmp
- scripts/send-targets.gmp
- scripts/send_delta_emails.gmp
- scripts/startAlertScan.gmp
This commit addresses a number of code style issues reported by `pep8`
and `pylint` to improve readability and work towards a more consistent
style for the GMP scripts.
> Address code style issues

- .circleci/config.yml
should fix failed test like this https://circleci.com/gh/greenbone/gvm-tools/43#tests/containers/0
> circleci: install dependencies also for tests

- .bandit
should fix this false positive https://app.codacy.com/app/greenbone/gvm-tools/pullRequest?prid=1784306
other tests can be added later, if needed.
> bandit: exclude tests which produce false positives

- gmp/gmp.py
- gmp/gvm_connection.py
Updated gmp.py and gvm_connection.py scripts allowing modification of tasks and targets
> Updated gmp/gvm_connection for modification of tasks/targets

- gmp/gvm_connection.py
Use the exec_command() without pty for SSH type connectios and use the
stdin and stout channels to send an receive the cmds and responses.
Avoiding the use of pty fixes the issue when the cmd is longer than 4096bytes.
> Commands through ssh can be longer than 4096 bytes.

- gmp/gmp.py
> Fix variable re-assignments

- setup.py
- removed old stuff needed for python 2
- added more classifiers
- use more general author
upload to test pypi looks like this: https://test.pypi.org/project/gvm-tools/
> refactored setup.py

- gmp/gvm_connection.py
Check not only if the length of the received data is less than
the buffer size, but also if it received the closing root element.
There is also a read_timeout to break the loop in case the closing
root element is never received or the server is disconnected.
> Fix issue #60 for unix socket connections.

- gmp/xml.py
Also, add method append_xml_str() to XmlCommandElement class.
> Convert create_*_command() methods to use the new Class XmlCommandElement.

- gmp/xml.py
Also, use lowercase for variable name.
> Convert modify_*_command() methods to use the new Class XmlCommandElement.

- gmp/protocols/gmpv7.py
- gmp/xml.py
Do the same for get_version_command(), help_command(), empty_trashcan_command()
and describe_auth_command().
> Add get_*_command() methods to GmpCommandFactory class and use them.

- gmp/protocols/gmpv7.py
- gmp/xml.py
> Add more *_command() methods to GmpCommandFactory class and use them

- CHANGELOG.md
- gvmtools/cli.py
- gvmtools/pyshell.py
* Display the version of python-gvm in gvm-cli and gvm-pyshell
* Pass version to gmp scripts
> API version

- scripts/send-delta-emails.gmp
- scripts/start-alert-scan.gmp
- scripts/start-multiple-alerts-scan.gmp
Fix various typos found by [codespell](https://github.com/codespell-project/codespell) 1.14
```
codespell . -S ".git,*.gif,*.png"
```
> Fix various typos.

- Pipfile
- Pipfile.lock
- setup.py
We have agreed on using python-gvm as name on all "platforms".
> Use python-gvm as package name too

- setup.py
Update the description displayed at pypi.
> Update description in setup file

- .circleci/config.yml
* Enhance re-usability of circleci config
> Update circleci config to use several python versions

- docs/conf.py
- docs/config.rst
- docs/glossary.rst
- docs/index.rst
- docs/install.rst
- docs/scripting.rst
- docs/tools.rst
Start a sphinx based user documentation for gvm-tools
Fixes #103 and #106
> Add user documentation for gvm-tools

- README.md
- docs/scripting.rst
- gvmtools/script.py
- scripts/pdf-report.gmp
- scripts/scan-new-system.gmp
Add section for GVM scripting and some cleanup
> Docs part #3

- gvmtools/config.py
- gvmtools/parser.py
- tests/test_parser.py
Ensure to not crash if a config file is missing.
> Don't crash if config file is missing

- gvmtools/cli.py
This fix an issue which caused to authenticate to an OSP socket
(which does not support authentication), if OSP protocol was
not specified and there is an username set in gvm-tools.conf.
> Add protocol argument to cli.py

- scripts/check-gmp.gmp
> Fix script.

- .circleci/config.yml
Lint all the python files
Linting the gmp scripts will follow.
> Circleci updates

- .circleci/config.yml
- scripts/.pylintrc
- scripts/check-gmp.gmp
- scripts/requirements.txt
- scripts/update-task-target.gmp
* Update scripts to be error and warning free.
* Run pylint on scripts at the CI.
> Lint gvm scripts

- scripts/application-detection.gmp
- scripts/cfg-gen-for-certs.gmp
- scripts/check-gmp.gmp
- scripts/clean-slave.gmp
- scripts/combine-reports.gmp
- scripts/create-dummy-data.gmp
- scripts/create-targets-from-host-list.gmp
- scripts/gen-random-targets.gmp
- scripts/monthly-report.gmp
- scripts/monthly-report2.gmp
- scripts/nvt-scan.gmp
- scripts/random-report-gen.gmp
- scripts/send-delta-emails.gmp
- scripts/send-schedules.gmp
- scripts/send-targets.gmp
- scripts/send-tasks.gmp
- scripts/start-alert-scan.gmp
- scripts/start-multiple-alerts-scan.gmp
- scripts/start-nvt-scan.gmp
- scripts/sync-assets.gmp
- scripts/update-task-target.gmp
Use consistent formatting for all gmp scripts by applying code
formatting via black.
> Format all gmp scripts with black

- scripts/check-gmp.gmp
Set the given path for the db.
> Fix cache arg

- CHANGELOG.md
- Pipfile.lock
Refresh the dependencies specified via the `Pipfile.lock` file to their latest versions.
**Checklist**:
> Refresh dependencies to their latest version

- CHANGELOG.md
- README.md
- gvmtools/parser.py
- tests/socket_help.snap
- tests/ssh_help.snap
- tests/test_parser.py
- tests/tls_help.snap
> Cli parser global args

- CHANGELOG.md
- gvmtools/cli.py
> Gvm cli error reporting

- .github/CODEOWNERS
> Set maintainers for gvm-tools

- Pipfile.lock
- gvmtools/cli.py
- gvmtools/pyshell.py
- gvmtools/script.py
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/gvm-tools/blob/master/CHANGELOG.md) Entry
> Support gmp selection

- CHANGELOG.md
- scripts/clean-sensor.gmp
> Use term sensor instead of slave

- CHANGELOG.md
- gvmtools/cli.py
> Allow to pretty print xml output in gvm-cli

- scripts/check-gmp.gmp
Added Error, if there are not the correct permissions for the cache path, fixes #209.
**Checklist**:
> Added Error, if there are not the correct permissions for the cache path

- CHANGELOG.md
**Checklist**:
Referring to PR #211
> Added CHANGELOG entry for the check_gmp script

- CHANGELOG.md
- scripts/random-report-gen.gmp
The script `random-report-gen.gmp` is able to add `host`, `os` and `application` data now, so the created reports are more realistic.
**Checklist**:
> Random data generation

- CHANGELOG.md
- scripts/random-report-gen.gmp
> Report generator updates

- CHANGELOG.md
- gvmtools/cli.py
Fix for https://github.com/greenbone/gvm-tools/issues/221
> Catch python exception.

- CHANGELOG.md
- gvmtools/script.py
As described in #221 and fixed for `gvm-cli`in #222 , this should also be added to `gvm-script`
**Checklist**:
> Catch exception in script.py

- CHANGELOG.md
- scripts/default_report_data.json
- scripts/random-report-gen.gmp
New parameter in the random-report-gen.gmp script by which we can add not_vuln host_details to hosts
**Checklist**:
> New parameter in the random-report-gen.gmp script

- .circleci/config.yml
All source code should be formatted with black.
**Checklist**:
- [n/a] Tests
- [n/a] [CHANGELOG](https://github.com/greenbone/gvm-tools/blob/master/CHANGELOG.md) Entry
> Run black --check on gvmtools sources and scripts

- docs/glossary.rst
- docs/install.rst
- docs/scripting.rst
Fixed some broken or redirected links.
**Checklist**:
> Fixed some broken or redirected links.

- CHANGELOG.md
- gvmtools/parser.py
- tests/ssh_help.snap
- tests/tls_help.snap
> Allow to specify the hostname in a config file

- CHANGELOG.md
- docs/glossary.rst
Update and add new items for GVM 11 changes to the glossary.
**Checklist**:
- [n/a] Tests
> Update glossary to changes in GVM 11

- docs/glossary.rst
GVM stands for Greenbone Vulnerability Management framework.
**Checklist**:
> Update GVM abbreviation

- CHANGELOG.md
- scripts/check-gmp.gmp.py
Fixed some problems in the check-gmp script.
This needs some refactoring all over ... will take a look at it later.
This is just a quick fix, for cx.
**Checklist**:
> Repair of the check-gmp script: no report list, Pathlib python 3.5

- gvmtools/cli.py
- gvmtools/parser.py
- gvmtools/pyshell.py
**What**:
Changes for black (in python3.6)
**Why**:
<to be up to date with the black dependency
**How**:
I've run
`poetry env use 3.6.5`
`poetry install`
`black gvmtools`
**Checklist**:
> Make black happy

- CHANGELOG.md
- scripts/pdf-report.gmp.py
**What**:
The content in the pdf-report script was not correct ... fixed it ... it is the tail of that tag ... really awkward oO
**Why**:
Script did not work as expected
**How**:
Found out why it was malformed ... by looking into the XML
**Checklist**:
> Corrected the report-pdf script

- README.md
**What**:
Inform customers that they can use the latest release with every supported GOS version.
**Why**:
It could be confusing that the release schedule is different for `gvm-tools` compared to GOS.
**How**:
**Checklist**:
> Updated the README with version information

- .circleci/config.yml
- scripts/check-gmp.gmp.py
- scripts/clean-sensor.gmp.py
- scripts/list-tasks.gmp.py
- scripts/random-report-gen.gmp.py
- scripts/scan-new-system.gmp.py
- scripts/send-targets.gmp.py
**What**:
Run CI for building the docs and linting the gm scripts.
**Why**:
Building the docs should always work and a PR breaking the docs should not be merged. Additionally gmp scripts should be checked and linted.
> Improve CI

- CHANGELOG.md
- gvmtools/helper.py
- tests/test_helper.py
**What**: I have added tests for the helper module. The helper module has now a test coverage of 100%. Also while testing I have discovered that the "authenticate" function raises and error if the username is None. I have fixed that bug, too.
**Why**: To increase test coverage and to increase the reliability of the code.
**How**: Just run the tests and run coverage.
**Checklist**:
> Added Tests for Helper Module

- tests/test_helper.py
**What**: Fixed the license header. Refactored tests of the functions into seperate TestCases
**Why**: License header was wrong. And refactored because of seperation of concerns
**Checklist**:
> Changes in PR 310

- CHANGELOG.md
- scripts/send-targets.gmp.py
**What**:
Fixing the `send-targets.gmp.py`-script facing the Issue #233 
**Why**:
The script did not work as expected.
**How**:
Corrected the keywords. that are passed to the gmp call.
**Checklist**:
> Send targets

- .circleci/config.yml
- CHANGELOG.md
- README.md
- poetry.lock
- pyproject.toml
**What**:
Dropping the support for Python 3.5 and 3.6, adding Python 3.9
**Why**:
* Python 3.5 is deprecated
**How**:
**Checklist**:
> Dropping the support for Python 3.5 and 3.6, adding Python 3.9

- CHANGELOG.md
- README.md
- gvmtools/helper.py
- scripts/application-detection.gmp.py
- scripts/cfg-gen-for-certs.gmp.py
- scripts/check-gmp.gmp.py
- scripts/clean-sensor.gmp.py
- scripts/combine-reports.gmp.py
- scripts/create-dummy-data.gmp.py
- scripts/create-targets-from-host-list.gmp.py
- scripts/delete-overrides-by-filter.gmp.py
- scripts/gen-random-targets.gmp.py
- scripts/list-tasks.gmp.py
- scripts/monthly-report.gmp.py
- scripts/monthly-report2.gmp.py
- scripts/nvt-scan.gmp.py
- scripts/pdf-report.gmp.py
- scripts/random-report-gen.gmp.py
- scripts/scan-new-system.gmp.py
- scripts/send-delta-emails.gmp.py
- scripts/send-schedules.gmp.py
- scripts/send-targets.gmp.py
- scripts/send-tasks.gmp.py
- scripts/start-alert-scan.gmp.py
- scripts/start-multiple-alerts-scan.gmp.py
- scripts/start-nvt-scan.gmp.py
- scripts/sync-assets.gmp.py
- scripts/update-task-target.gmp.py
- tests/test_helper.py
**What**:
**Why**:
**How**:
* e.g. replace `quit()` by `sys.exit()` (because of bad practice)
* remove code duplicates and added these reusable functions to the `helper.py` class.
* Added tests for these
**Checklist**:
> Improve scripts

- scripts/create-consolidated-report.gmp.py
- tests/scripts/test_create_consolidated_report.py
**What**:
* using `last` instead of `created` for task filter ... we want the last report not the date the task was created
* added filter-id argument for result filter ...
**Why**:
**How**:
**Checklist**:
> Monthly report scripts

- scripts/create-consolidated-report.gmp.py
- tests/scripts/test_create_consolidated_report.py
**What**:
* Changed the xpath so hosts are added to the report correctly
**Why**:
**How**:
**Checklist**:
> Host details in the consolidate reports script

- CHANGELOG.md
- RELEASE.md
**What**:
...
**Why**:
**How**:
**Checklist**:
> Update Readme and Changelog

- gvmtools/__init__.py
- gvmtools/cli.py
- gvmtools/config.py
- gvmtools/parser.py
- gvmtools/pyshell.py
- gvmtools/script.py
- tests/__init__.py
- tests/scripts/__init__.py
- tests/scripts/test_send_schedules.py
- tests/scripts/test_send_tasks.py
- tests/scripts/test_start_alert_scan.py
- tests/test_config.py
- tests/test_parser.py
**What**:
**Why**:
**How**:
**Checklist**:
> Update copyright year

- poetry.lock
- pyproject.toml
**What**:
**Why**:
**How**:
**Checklist**:
> Require at least a v20 python-gvm version

- CHANGELOG.md
- scripts/combine-reports.gmp.py
**What**:
**Why**:
**How**:
**Checklist**:
> In assets for combine-reports

- scripts/create-cve-report-from-json.gmp.py
**What**:
Fix the json to cve scan script
**Why**:
**How**:
**Checklist**:
> Fix the json to cve scan script

- CHANGELOG.md
**What**:
Add an entry for the community PR https://github.com/greenbone/gvm-tools/pull/373 to the changelog.
**Why**:
Every PR should get a changelog entry.
**How**:
**Checklist**:
- n/a Tests
- n/a Documentation
> Update CHANGELOG for community patch

- README.md
- gvmtools/cli.py
This PR resolves https://github.com/greenbone/gvm-tools/issues/429.
I have updated the documentation everywhere I noticed it differing from the actual behavior, but I may have missed some places.
> gvm-cli: update documentation on reading file (resolves #429)

- .github/workflows/ci-python.yml
**What**:
Start using GitHub Actions as CI.
This PR or another PR must extend the config to build the docs and lint the scripts too as we do with CircleCI currently.
**Why**:
**How**:
**Checklist**:
> Start to use GitHub actions

- .github/workflows/deploy-pypi.yml
**What**:
Upload release via GitHub Action workflow
**Why**:
**How**:
**Checklist**:
> Deploy via GitHub Action

- gvmtools/cli.py
**What**:
**Why**:
* Pylint was unhappy
**How**:
* used the already existing authenticate function in helper class
**Checklist**:
> Refactor gvm-cli file and avoid false-positive no-member pylint error

- .github/workflows/release-pontos.yml
- poetry.lock
- pyproject.toml
**What**:
Use pontos release and our bot to create a release automatically by using a make-release label.
**Why**:
**How**:
**Checklist**:
> Allow to create releases via our bot

- CHANGELOG.md
- gvmtools/cli.py
**What**:
* fix GMP authentication for `gvm-cli`
**Why**:
* Error is described here: https://community.greenbone.net/t/authentication-failed-with-gvm-cli-same-creds-work-on-the-web-ui/9424
* I messed up the authentication for `gvm-cli` previously here: https://github.com/greenbone/gvm-tools/pull/461
**How**:
**Checklist**:
> Fix authentication for gvm-cli.

- docs/index.rst
**What**:
Update Python release
**Why**:
See https://github.com/greenbone/gvm-tools/blob/master/pyproject.toml#L40
**How**:
N/A
**Checklist**:
> Update Python release

- scripts/create-consolidated-report.gmp.py
**What**:
Corrected the output error "Combining {len(reports)} found reports."
in consolidated-report.gmp.py.
**Why**:
This is a small bug-fix.
Addresses AP-1819.
**How**:
Ran the script consolidated-report.gmp.py with different parameters.
**Checklist**:
> Corrected an output error in consolidated-report.gmp.py.

- docs/install.rst
**What**:
Fixing an error that occurred when building the documents
**Why**:
Error on docs build
**How**:
**Checklist**:
> fix syntax of docs/install.rst

- poetry.lock
- scripts/create-targets-from-host-list.gmp.py
**What**:
Fixing the `create-targets-from-host-list.gmp.py` script
**Why**:
* Port List or Port Range is required for `python-gvm` API call `create_target`.
See https://community.greenbone.net/t/create-targets-from-cli/11675
**How**:
**Checklist**:
> Fix: Create Targets from Host List script

- pyproject.toml
**What**:
Change: Use greater or equal then for dependencies with calver
**Why**:
This allows to loosen the dependencies especially because these are dev
dependencies.
**How**:
**Checklist**:
> Change: Use greater or equal then for dependencies with calver

- gvmtools/cli.py
- gvmtools/config.py
- gvmtools/helper.py
- gvmtools/parser.py
- gvmtools/pyshell.py
- gvmtools/script.py
- poetry.lock
- pyproject.toml
- tests/__init__.py
- tests/scripts/__init__.py
- tests/scripts/test_combine_reports.py
- tests/scripts/test_create_consolidated_report.py
- tests/scripts/test_send_schedules.py
- tests/scripts/test_send_targets.py
- tests/scripts/test_send_tasks.py
- tests/scripts/test_start_alert_scan.py
- tests/test_config.py
- tests/test_helper.py
- tests/test_parser.py
**What**:
Add autohooks plugin isort
**Why**:
Sort all import with isort and autohooks-plugin-isort
**How**:
**Checklist**:
> Add autohooks plugin isort

- .github/workflows/github-pages.yml
**What**:
Add: Deploy docs to GitHub pages too
**Why**:
This will allow to replace readthedocs at the end.
**How**:
**Checklist**:
> Add: Deploy docs to GitHub pages too

- README.md
- docs/index.rst
- docs/scripting.rst
- pyproject.toml
**What**:
* Update the README and docs for the current terms
* Use links to greenbone.github.io
* Update pip installation in README
* Set language for code examples in README
**Why**:
Update outdated information
**How**:
**Checklist**:
> Change: Update links and terms in README and docs

- docs/config.rst
- docs/connectiontypes.rst
- docs/glossary.rst
- docs/scripting.rst
- docs/tools.rst
**What**:
* Use current terms
* Remove old stuff like openvasmd
**Why**:
Fit for new naming schema
**How**:
**Checklist**:
> Update and improve docs

- .docker/Dockerfile
- .docker/entrypoint.sh
- .github/workflows/container.yml
**What**:
Add a Dockerfile and GitHub actions workflow to build and upload
container images to Dockerhub automatically.
DEVOPS-347
**Why**:
Provide an image for gvm-tools for CLI access to gvmd.
**How**:
**Checklist**:
> Add: Build container image for gvm-tools

- .github/dependabot.yml
**What**:
Add: Update GitHub actions via dependabot too
**Why**:
Maintain action versions via dependabot
**How**:
**Checklist**:
> Add: Update GitHub actions via dependabot too

- .github/workflows/ci-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/github-pages.yml
- .github/workflows/release-pontos.yml
Use generic reusable workflows
Use our new generic reusable workflows where possible.
> Change: Use generic reusable workflows

- scripts/create-consolidated-report.gmp.py
- tests/scripts/test_create_consolidated_report.py
This adds the command line options ++container-id and ++new-container-name to the create-consolidated-report script.
The ++container-id option checks if a container task with the given id exists and upload the consolidated report there instead of creating a new task.
The ++new-container-name defines the name of the container task when creating a new one instead of using an automatically generated name.
To give users more control where the report is uploaded.
GEA-372
> Add: New create-consolidated-report container opts

- .bandit
- README.md
- docs/conf.py
- gvmtools/__init__.py
- gvmtools/cli.py
- gvmtools/config.py
- gvmtools/helper.py
- gvmtools/parser.py
- gvmtools/pyshell.py
- gvmtools/script.py
- tests/__init__.py
- tests/scripts/__init__.py
- tests/scripts/example_schedules.xml
- tests/scripts/example_target.xml
- tests/scripts/example_task.xml
- tests/scripts/get_alerts.xml
- tests/scripts/get_scan_configs.xml
- tests/scripts/invalid_xml.xml
- tests/scripts/test_combine_reports.py
- tests/scripts/test_create_consolidated_report.py
- tests/scripts/test_send_schedules.py
- tests/scripts/test_send_targets.py
- tests/scripts/test_send_tasks.py
- tests/scripts/test_start_alert_scan.py
- tests/test_config.py
- tests/test_helper.py
- tests/test_parser.py
Remove obsolete config file and update copyright
Maintenance
> Project cleanup

- gvmtools/cli.py
Replace validate_xml_string with parse_xml function
validate_xml_string got removed from the latest release.
> Fix: Replace validate_xml_string with parse_xml function

- .github/workflows/ci-python.yml
Add Codecov token to CI workflow
GEA-604
> Add Codecov token to CI workflow

- .github/workflows/ci-python.yml
- .github/workflows/codeql-analysis-python.yml
- .github/workflows/container.yml
- .github/workflows/conventional-commits.yml
- .github/workflows/dependency-review.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/sbom-upload.yml
Changed the vX notation for actions to the actual hashcode.
The actions become immutable this way. Dependabot can update the hashcode to the last released version on it's own.
DEVOPS-1316
> Change: Version to pinned dependencie

- .github/workflows/changelog.yml
Add workflow for list unreleased changes
Allow to determine the unreleased changes.
https://jira.greenbone.net/browse/GEA-984
> Add workflow for list unreleased changes

- scripts/README.md
Update description of generate-random-reports.gmp.py
> Update description of generate-random-reports.gmp.py

- scripts/export-xml-report.gmp.py
Made the script "export-xml-report.gmp.py" work.
This was a bug.
GEA-1242
Tested manually on my local development system.
> Made the script "export-xml-report.gmp.py" work.
