- setup.py
Currently installing gvm-tools with pip from Python 2.7 works, but the result installation is non-functional.
This should prevent gvm-tools from being installed with pip from Python < 3.
> Exit during setup if a Python version less than 3 is detected

- gmp/clients/gvm_cli.py
The script should follow the POSIX convention of zero for success and nonzero for error.
> Use exit code 1 only when an exception occurred, exit code 0 otherwise

- gmp/gvm_connection.py
This commit adds support for accessing the response to a request without
using the `checkCommandStatus` method. If the attribute `raw_response`
is set to `True` for a connection, the method `read` will return the
response directly instead of processing it with `checkCommandStatus`.
> Add support for accessing the raw response

- gmp/gmp.py
This pull request adds support for all parameters specified in the OMP/GMP 7.0 specification to the `createTargetCommand` method.
Mandatory parameters are expected as named parameters, optional parameters are expected in `kwargs` parameter with keywords matching the name of the element in the specification.
> Support the entire set of possible `create_target` parameters

- gmp/gvm_connection.py
This commit causes an OSError be re-raised in the `send` method after
logging it as an OSError is asssumed to be fatal to the control flow.
Otherwise OSErrors like a closed socket will be silently caught, causing
the client to wait for a response to something it was never able to send.
> Re-raise OSError

- .circleci/config.yml
- .coveragerc
This PR adds support for running unit tests automatically in the CircleCI framework and for submitting the coverage data for said unit tests to the Codecov reporting platform.
> Run unit tests in Circle CI and collect coverage data

- gmp/gvm_connection.py
- tests/connectiontests/gmp_unittest.py
This commits removes two unused `import`s as reported by Codacy.
> Remove unused imports

- gmp/gmp.py
This commit replaces the `assert` statements with conditionals raising a
`ValueError` if their condition is not met.
As the statements were seemingly intended to enforce interface
constraints, they should no rely on `assert` as this statement is
removed in its entirety when compiling to optimised byte code.
> Replace assertions with ValueErrors

- gmp/gmp.py
This commit adds the previously missing mandatory `credential_id`
attribute to the `modify_credential` command generated by
`modifyCredentialCommand`.
> Include credential_id in modify_credential command

- gmp/clients/gvm_dialog.py
- gmp/clients/gvm_pyshell.py
- gmp/gvm_connection.py
This commit removes parenthesis following keywords like `while`,
`return` and `if` which are not necessary in Python and should not be
used, for simplicity.
> Remove unnecessary parens

- gmp/clients/gvm_dialog.py
- gmp/clients/gvm_pyshell.py
- gmp/gmp.py
This commits uses `isinstance()` instead of `type()` for testing the
type of objects as recommended by the Python documentation.
> Use isinstance() for typechecking

- gmp/gmp.py
This commit removes the outdated `FIXME` comment in
`modifyCredentialCommand` which got resolved by a concurrent pull
request.
> Remove outdated FIXME comment

- gmp/gmp.py
This commits adds proper handling of the `copy` and `comment` attributes
to the `createAlertCommand` method so that the `create_alert` command
string includes the corresponding elements as well if necessary.
> Support 'copy' and 'comment' for alert creation

- scripts/send_delta_emails.gmp
This commit removes two instances of statements which were commented out
but preceded by a comment indicating they should be used for debugging.
As a general rule, if additional logging should be needed in GMP scripts
it should be controlled through parameters passed to `gvm_pyshell` and
not require source code changes.
> Remove commented-out debug statements

- gmp/gmp.py
The API has a serious problem with creating the commands. You always concatenate strings with the XML tags, but you never encode the values. This works as long as you don't use any XML specific characters. I got a problem when I tried to create a task with an ampersand (&) in the name. So you should always encode all inserted strings!
I fixed the problem for the "createTaskCommand" on a clean way, as I only had the problem with that command. Maybe you could fix all the other commands, too?
I'll open an issue for that.
> Fix: Correct XML encoding for commands. First step: createTaskCommand

- gmp/gmp.py
- requirements.txt
- setup.py
Use the XML library to build an XML tree instead of string concatenation.
This encodes all inserted string and avoids problems with especial characters.
>  Correct XML encoding for create and modify commands in gmp

- README.md
- gmp/clients/gvm_cli.py
- gmp/gvm_connection.py
Now it is possible to use gvm-cli to connect to an ospd-wrapper using a tls connection.
It also fixed an issue with the default port for tls connection, now it is not fixed anymore.
> Gvm-cli tls connection accept certs as arguments.

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- README.md
Pipenv is a really nice tool to separate python packages into environments without having to handle the environment itself.
* It's documentation can be found at https://pipenv.readthedocs.io/en/latest/
* It's already suggested at the python packaging guide at https://packaging.python.org/tutorials/managing-dependencies/ for managing the dependencies. 
* It uses https://github.com/pypa/pipfile to maintain its runtime **and** development dependencies.
* A good introduction to pipenv can be found at https://realpython.com/pipenv-guide/
> Use pipenv

- Pipfile
- Pipfile.lock
The gvm-dialog script requires pythondialog.
> Add pythondialog as runtime/install dependency

- requirements.txt
The file is obsolete since switching to use Pipfile and Pipfile.lock
with pipenv.
> Remove requirements.txt file

- gmp/__init__.py
Uses should always import GmpError from gmp.error like
```python
from gmp.error import GmpError
```
> Remove GmpError from main gmp module

- docs/api.rst
- gmp/protocols/base.py
- gmp/protocols/gmpv7.py
- gmp/protocols/latest.py
- gmp/protocols/ospv1.py
Currently osp is supported by creating a Gmp connection. But calling gmp.get_tasks on a connection to a ospd server would fail of course. Therefore create a new Osp class to support communication to osp daemons. Currently the Osp class is only a stub that should be extended with osp specific command methods.
> Add own class for OSP support

- scripts/nvt-scan.gmp
- scripts/random-report-gen.gmp
- scripts/send-targets.gmp
- scripts/start-alert-scan.gmp
- scripts/start-multiple-alerts-scan.gmp
- scripts/start-nvt-scan.gmp
- scripts/update-task-target.gmp
This commit addresses a number of instances in the GMP scripts where the
`is` and `is not` operators were used in comparisons.
In all cases, a comparison based on the value of the objects was
desired. However, `is` and `is not` test for object identity and need to
be replaced with the `==` and `!=` to test for object value.
> Use equality tests instead of object identity tests

- gvmtools/cli.py
- gvmtools/pyshell.py
This commit makes the output of `--version` (or `-V`) more consistent
with other CLI tools.
> Improve `--version` output

- CHANGELOG.md
- gvmtools/cli.py
- gvmtools/pyshell.py
Makes the style used by the CLI help messages of the tools provided by `gvm-tools`
more consistent, both internally and with other CLI applications.
> Improve output of `--help`

- CHANGELOG.md
- gvmtools/cli.py
- gvmtools/parser.py
- gvmtools/pyshell.py
Add a parser class for creating a common argument parser for both clis
of gvm-tools.
This PR also fixes 
* loading the defaults from the config file
* Ignores config file if not exists
* displaying all possible command arguments for --help, ssh --help, socket --help and tls --help
> Use a common parser for both cli tools

- gvmtools/cli.py
Removing newlines can cause problems with text blocks where
newlines are important, like PEM file imports.
> Do not remove newlines from XML

- setup.py
using python version from README.
This will prevent install using unsupported python versions.
> Clearify python version dependency

- .pylintrc
Disable the pylint check for bad-continuation (C0330) since it is a bug
in pylint which clashes with the `black` formatting which is now
enforced.
> Sync .pylintrc with template, disabling bad-continuation check

- gvmtools/parser.py
- tests/test_parser.py
Additional arguments despite the --protocol arg are added after the
main/root arguments and after the connection type. Therefore
add_argument must add the arguement to all subparsers instead of the
main parser.
> Fix parsing additional arguments

- CHANGELOG.md
- gvmtools/helper.py
- gvmtools/pyshell.py
- gvmtools/script.py
- setup.py
Add new CLI gvm-script to run gmp scripts. Running scripts only should be removed from gvm-pyshell in future.
> Gvm script

- CHANGELOG.md
- gvmtools/config.py
- gvmtools/parser.py
- tests/test.cfg
- tests/test_auth.cfg
- tests/test_config.py
Fixes #158 
This PR reintroduces parsing of the [Auth] section for backwards compatibility. I wasn't aware of the gvm-tools chapter in the docs and of the documented config. Therefore it's better to keep backwards compatibility and only to deprecate the old setting.
The setting must be converted in the following way
Old:
```
[Auth]
gmp_username=foo
gmp_password=bar
```
New:
```
[gmp]
username=foo
password=bar
> Add improved handling of config settings

- docs/requirements.txt
For building the docs on reathedocs we need a requirements.txt file
currently.
> Add a requirements.txt file for building docs on rtd

- gvmtools/config.py
- gvmtools/parser.py
- tests/test_config.py
If a config file (like by default ~/.config/gvm-tools.cfg) does not exist the parser will ignore it instead of raising an exception with all CLIs
> Fix loading config file

- scripts/check-gmp.gmp
Use get_report instead get_reports from gmpv* to get just one report.
Fix to_int, since the default value is always None.
> Fix check-gmp.gmp script

- CHANGELOG.md
- gvmtools/cli.py
- gvmtools/helper.py
- gvmtools/pyshell.py
- gvmtools/script.py
Add function that raises a RuntimeError if one of our tools is run a
root user. Running the tool as root is never required and is always a
bad habit.
**Checklist**:
> Don't allow to run cli tools as root user

- gvmtools/parser.py
- gvmtools/script.py
- scripts/check-gmp.gmp
- tests/test_parser.py
- Add method to parse only known arguments to gvm-tools. 
This allows to use the unknown e.g. for a script, with the gvm-script tool.
This change does not modify the behavior for gvm-cli neither for gvm-pyshell. Therefore, if an known argument is given for this last ones, it will exit with an error, showing the help text.
- Improve args parser for check-gmp.gmp.
It use now the '-' char as prefix, which is consistent with the gvm-tools parser.
It still use parse_args() method for both the known and unknown args separately, to allow detection of not recognized args for the script.
- Add test for the new parse_known_args() method.
> Gvm tools parser

- CHANGELOG.md
- scripts/update-task-target.gmp
Use correct API to get single task and targets.
Fixes #187
**Checklist**:
- [n/a] Tests
> Fix getting task and targets at update-task-target gmp script

- .circleci/config.yml
Only generate coverage statistics when running tests with python 3.7.
> Update circleci config to run coverage detection only once

- CHANGELOG.md
- gvmtools/cli.py
Just change infile argument to be a string and load the file in a
function. This will create better error massges, no tracebacks and fixes
passing unknown arguments.
**Checklist**:
> Don't use argparse to load infile

- scripts/random-report-gen.gmp
A small tweak to the method for uploading the generated reports.
The shortcut of creating the task by importing the first report is no
longer supported in GMP >= 9, so create the container task first before
adding reports to it.
This change is backwards compatible with GMP 8 as well.
**Checklist**:
> Make 'random-report-gen.gmp' GMP9 compatible

- CHANGELOG.md
- gvmtools/cli.py
Allow to measure the duration of a xml command execution.
**Checklist**:
> Add --duration argument to gvm-cli

- CHANGELOG.md
- scripts/update-task-target.gmp
It seems, that two targets can not have the same name (anymore (?)). The gmp responses that the Target already exists. This-why the copied target gets the suffix `_copy`.
**Checklist**:
> Fixes the update-task-target script.

- CHANGELOG.md
- gvmtools/parser.py
- gvmtools/pyshell.py
- gvmtools/script.py
- tests/socket_help.snap
- tests/test_parser.py
According to: https://community.greenbone.net/t/socket-error/3534
This will fix the error, that sockpath can't be used properly. This will not fix the issue, that the default path might be incorrect @bjoernricks. 
**Checklist**:
> dest should do the trick, so that sockpath will be stored in socketpath

- Pipfile
- Pipfile.lock
Now that `python-gvm` has been released and is available from pypi, the `Pipfile` can specify the dependency properly.
**Checklist**:
> Update dependencies in Pipfile

- tests/__init__.py
- tests/test_parser.py
Added a class that suppresses the output of tested methods when running tests with `python unittest`. Refering to #210. 
**Checklist**:
> Suppressing output in tests

- Pipfile.lock
- gvmtools/config.py
- gvmtools/parser.py
- setup.py
- tests/ssh_help.snap
- tests/test_parser.py
- tests/tls_help.snap
I thought this would be more consistent for all the default parameter.
They are now all imported from the `python-gvm` and this pull requests is only valid in combination with https://github.com/greenbone/python-gvm/pull/185
**Checklist**:
> Unify config params

- CHANGELOG.md
- gvmtools/parser.py
With this change you can use case insensitive loglevel like `debug` for `DEBUG` etc ...
**Checklist**:
> case-insensitive log level

- CHANGELOG.md
- scripts/scan-new-system.gmp.py
**What**:
Fixed scan-new-system.gmp.py for supporting gmp-20.08.
After gmp-20.08, CREATE_TARGET will need PORT_LIST or PORT_RANGE.
**Why**:
When I run "scan-new-system.gmp.py", I got following error;  
```Response Error 400. One of PORT_LIST and PORT_RANGE are required```
Then I found After gmp-20.08, [CREATE_TARGET will need PORT_LIST or PORT_RANGE](https://docs.greenbone.net/API/GMP/gmp-20.08.html#changes).
**How**:
1. Run ```/usr/local/bin/gvm-script --gmp-username admin --gmp-password [pass] tls --port=9390 --host=127.0.0.1 /data/gvm-tools/scripts/scan-new-system.gmp.py [Target] "4a4717fe-57d2-11e1-9a26-406186ea4fc5"```, and it worked to create new scan job.
2. Run ```/usr/local/bin/gvm-script --gmp-username admin --gmp-password [pass] tls --port=9390 --host=127.0.0.1 …
```
> Fixed scripts/scan-new-system.gmp.py for supporting gmp-20.08.

- CHANGELOG.md
- scripts/send-targets.gmp.py
**What**:
Fixed send-targets.gmp.py script because alive_test needs to be enum in create_target.
**Why**:
Now alive_test needs to be enum in create_target function. And send-targets.gmp.py was not support it.
When XML is <alive_tests>Conside Alive</alive_tests> or this kind of thing, the script could not handle it.
**How**:
I exported several XML from target with several "alive_test", and use it as template to create target by using fixed send-targets.gmp.py. It worked fine.
**Checklist**:
> Fixed  send-targets.gmp.py script because alive_test needs to be enum in create_target.

- CHANGELOG.md
- scripts/README.md
- scripts/send-schedules.gmp.py
**What**:
Fixed send-schedules.gmp.py.
**Why**:
Because it could only import `<timezone_abbrev>`, not `<timezone>` which is exported from GVM Console.
Also, removed `targethost` arg from example/README because the script only need 1 arg(XML file).
**How**:
Use exported schedule data from GVM Console as template, and send it with several parameter by using fixed script. It works fine.
**Checklist**:
- [x ] [CHANGELOG](https://github.com/greenbone/gvm-tools/blob/master/CHANGELOG.md) Entry
> Fixed send-schedules.gmp.py because it couldn't import <timezone>.

- CHANGELOG.md
- gvmtools/pyshell.py
Added `pretty_print` to `pyshell` by default, so it does not need to be manually imported ...
**What**:
**Why**:
Personally I use this function frequently and I think this is a nice addition to pyshell.
**How**:
Added `pretty_print` to the variables.
**Checklist**:
> Added pretty_print to pyshell by default.

- docs/install.rst
**What**:
Run pip as a module from the Python3 interpreter. In this case it
doesn't matter if pip for Python3 is installed as pip3.
**Why**:
Create easy to follow installation instructions.
> Improve docs for running pip with Python 3

- CHANGELOG.md
- gvmtools/parser.py
- tests/test_parser.py
**What**: I've added tests for the parser module. It has a test coverage of 100% now. Also I've fixed a bug where `TypeError` will be thrown if port of SSHConnection is set to None. But I don't think this is an issue in this repository. I've added a PR in the `python-gvm` repository to address this issue ([https://github.com/greenbone/python-gvm/pull/321](https://github.com/greenbone/python-gvm/pull/321)). I've also opened an [issue](https://github.com/greenbone/python-gvm/issues/320)
**Why**: To increase test coverage and code reliability
**How**: I've added tests
**Checklist**:
> Added tests for parser module to reach 100% code coverage

- CHANGELOG.md
- scripts/pdf-report.gmp.py
**What**:
Avoid crashing with a base64 padding error.
**Why**:
It can be possible that `gvmd` is returning empty content for the pdf
report format if not all dependencies like latex are installed or if the
report doesn't contain any results because there was an scanner error.
In this case give a more detailed and explicit error message instead of
failing when the non available content is tried to be converted.
**How**:
Not tested yet but it is a simple check.
**Checklist**:
- [n/a] Tests
> Avoid crashing with unspecific error

- CHANGELOG.md
- scripts/combine-reports.gmp.py
- tests/scripts/__init__.py
- tests/scripts/test_combine_reports.py
- tests/scripts/test_send_targets.py
**What**:
Fixed the `combine-reports.gmp.py` script. It is [not possible](https://github.com/greenbone/python-gvm/pull/377) to create a task with `import_report()` anymore.
Added tests for this scirpt.
**Why**:
**How**:
**Checklist**:
> Fix combine-reports script and add tests for it

- docs/glossary.rst
**What**:
Extend the glossary in the docs
**Why**:
The glossary of gvm-tools is references several times at out community
forum. Therefore it should contain explanations for our newest
abbreviations and terms.
**How**:
```
poetry shell
cd docs
make html
firefox build/html/glossary.html
```
**Checklist**:
> Update and extend the glossary of the docs

- scripts/application-detection.gmp.py
- scripts/cfg-gen-for-certs.gmp.py
- scripts/check-gmp.gmp.py
- scripts/create-dummy-data.gmp.py
- scripts/create-targets-from-host-list.gmp.py
- scripts/delete-overrides-by-filter.gmp.py
- scripts/send-delta-emails.gmp.py
- scripts/start-nvt-scan.gmp.py
- scripts/sync-assets.gmp.py
- scripts/update-task-target.gmp.py
With Python 3.8+ we receive warnings like:
./application-detection.gmp.py:22: SyntaxWarning: "is not" with a literal. Did you mean "!="?
**What**:
Fix SyntaxWarning of Python 3.8+ for use of "is" and "is not" with literals.
**Why**:
Have no SyntaxWarnings
**How**:
Replaced "is" with "==" and "is not" with "!="
**Checklist**:
> Fix Python 3.8 SyntaxWarnings for scripts

- scripts/create-cve-report-from-json.gmp.py
From codespell:
```
./gvm-tools/scripts/create-cve-report-from-json.gmp.py:393: informations ==> information
```
There is no `informations` in the English language, it's just "information".
> Fix a typo.

- CHANGELOG.md
- scripts/combine-reports.gmp.py
- scripts/create-consolidated-report.gmp.py
**What**:
Add ignore_pagination to get_report calls
**Why**:
Otherwise the reports with more than `rows` results will get cutted ...
**How**:
**Checklist**:
> Add ignore_pagination to get_report calls

- CHANGELOG.md
- scripts/bulk-modify-schedules.gmp.py
**What**:
This script allows changing the timezone and icalendar data of multiple
schedules selected by a filter.
**Why**:
**How**:
Tested by creating several test schedules and running the scripts to modify the timezone.
**Checklist**:
> Add script bulk-modify-schedules.gmp.py

- CHANGELOG.md
- pyproject.toml
**What**:
Using `poetry-core` allows distribution packages to depend only on the build backend.
**Why**:
[`poetry-core`](https://github.com/python-poetry/poetry-core) is intended to be a light weight, fully compliant, self-contained package allowing PEP 517 compatible build frontends to build Poetry managed projects.
**How**:
Build with `poetry-core`: https://github.com/NixOS/nixpkgs/pull/137031
**Checklist**:
> Switch to poetry-core

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci-python.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/release-pontos-manually.yml
- .github/workflows/release-pontos.yml
- gvmtools/parser.py
- poetry.lock
- pyproject.toml
- tests/test_parser.py
**What**:
**Why**:
#702 
**How**:
**Checklist**:
> Fix: `pyproject.toml` dependencies, more improvements.

- scripts/default_report_data.json
- scripts/generate-random-reports.gmp.py
**What**:
This adds a --with-descriptions option to the generate-random-reports script to also generate
descriptions for the results and adds the source type to the generated host details.
**Why**:
Including the new fields makes the generated reports more like real reports.
**How**:
Running the script to generate a report on a GEA.
**Checklist**:
> Add --with-descriptions and host details source types to generate-random-reports

- .github/workflows/ci-python.yml
- .github/workflows/github-pages.yml
Fix workflows and enable poetry caching
Currently installing the furo sphinx theme with poetry 1.4.1 is broken. Therefore stick with poetry 1.4.0 for now. Use cache for faster CI runs.
> Fix workflows and enable poetry caching

- gvmtools/helper.py
- gvmtools/parser.py
- poetry.lock
- tests/ssh_help.3.10.snap
- tests/ssh_help.snap
* When gvm-tools runs in a CI or similar, we should avoid waiting for user-input
GEA-170
> Add: Auto-allow host for SSH connection

- pyproject.toml
fix for https://github.com/greenbone/gvm-tools/issues/966
> Fix for https://github.com/greenbone/gvm-tools/issues/966

- .github/workflows/conventional-commits.yml
Set permissions for conventional commits workflow
The conventional commits workflows requires write permissions for creating PR comments and read permissions to the repo contents.
> Fix: Set permissions for conventional commits workflow

- scripts/certbund-report.gmp.py
- scripts/requirements.txt
- scripts/ssv_csv.py
* Add script, previously written, to gvm-tools
* Script searches Reports for CERT-Bund Advisory-Occurrences and parses them into a CSV
**NOTE:** Did only run pylint/black, no refactor so far.
* Add script to version control, so it doesn't get lost
> Add: CERT-Bund Advisory script, parsing reports to CSV

- .docker/Dockerfile
Adjust docker image for Debian Bookworm
Debian Bookworm is blocking system wide Python package installations by default. Adjust the Dockerfile to install gvm-tools correctly again.
> Change: Adjust docker image for Debian Bookworm

- README.md
- docs/install.rst
Add installation instructions using pipx because of PEP 668
With current distributions a simple `pip install` is no longer possible because of PEP 668. Therefore recommend the usage of pipx for installing gvm-tools.
> Add installation instructions using pipx because of PEP 668

- docs/Makefile
- poetry.lock
- pyproject.toml
Allow to auto re-build the docs on changes via livehtml
Introduce a new makefile target livehtml that re-builds the docs automatically via the sphinx-autobuild package in the background.
It's easier and faster to write docs when they are updated automatically on every change.
> Add: Allow to auto re-build the docs on changes via livehtml

- .github/workflows/ci-python.yml
- README.md
- docs/index.rst
- poetry.lock
- pyproject.toml
Drop support for Python 3.7 and 3.8
Require Python 3.9 as minimum Python version. 3.7 is end of life already and we agreed on not supporting 3.8 anymore too.
> Remove: Drop support for Python 3.7 and 3.8

- scripts/send-delta-emails.gmp.py
- scripts/start-alert-scan.gmp.py
Some formatted strings were missing the declaration.
> Fixed missing f character to declare formatted strings

- scripts/check-gmp.gmp.py
Some superfluos print statements are removed from check-gmp.gmp.py that were presumably added for in-development testing and accidentally left in.
GEA-141
> Fix: Remove superfluous output from check-gmp

- scripts/application-detection.gmp.py
The script application-detection.gmp.py will now get the report
details and extract the host IP addresses correctly.
The application-detection script now requests details for each report
individually with minimum results, which is usually faster for gathering
the host data and ensures all hosts are included.
Also, only hosts where a matching app was found are output.
GEA-249
> Fix application detection

- .github/workflows/ci-python.yml
- gvmtools/cli.py
- gvmtools/config.py
- poetry.lock
- pyproject.toml
- scripts/certbund-report.gmp.py
- scripts/check-gmp.gmp.py
- scripts/combine-reports.gmp.py
- scripts/generate-random-reports.gmp.py
- scripts/ruff.toml
- scripts/send-delta-emails.gmp.py
- scripts/ssv_csv.py
- scripts/start-multiple-alerts-scan.gmp.py
- scripts/sync-hosts.gmp.py
- tests/scripts/__init__.py
Replace pylint with ruff
Use ruff instead of pylint because ruff is so much faster.
> Change: Replace pylint with ruff

- scripts/generate-random-reports.gmp.py
Fix param use in generate-random-reports
The n_results param in the generate_reports function was not used correctly.
> Fix: Fix param use in generate-random-reports

- scripts/generate-random-reports.gmp.py
* Fixed the logic for setting names of generated operating systems.
Names for generated operating systems were being cut off after the first letter.
* Checked with pylint.
* Tested manually by comparing generated reports from before and after the fix.
* Test environment: gvm-cli 23.10.0 (API version 23.10.1) & GOS 22.04.15
> Fix: Do not truncate operating system names

- scripts/create-consolidated-report.gmp.py
When running `create-consolidated-report.gmp`, log task id in case of failure to get last report for the given time period.
Helps in debugging and resolving script errors.
GEA-660
> Change: Log task id on failure to get last report in time period.

- scripts/cfg-gen-for-certs.gmp.py
Replace the deprecated method `modify_scan_config`
Replace `modify_scan_config` with `modify_scan_config_set_nvt_selection` and improve error handling
The method `modify_scan_config` is now deprecated. Improved error handling allows the script to skip "whole-only" families and continue instead of crashing.
GEA-653
> Fix: Fix scan config creation from CERT-Bunds.

- poetry.lock
Update lock file after dropping typing_extensions.
To remove typing_extensions from dependencies and make use of latest python-gvm version
GEA-638
> Update lock file.

- scripts/list-tasks.gmp.py
- tests/scripts/test_list_tasks.py
Extend list-tasks script with average and last scan duration time.
Customer requests a script that gives the name, average duration and duration of the last scan of all tasks available to a user. 
GEA-661
> Change: Extend list-tasks with average and last scan duration time.

- scripts/create-consolidated-report.gmp.py
Consolidated report can now skip tasks without reports in the given period.
The task filter allows for tasks whose last report fall outside the given interval. See commit [3067417](https://github.com/greenbone/gvm-tools/commit/3067417987f8025bf1d348e1cb99faaef6cdfb61).
If such tasks has no reports in the given period, the script will fail when getting the last report. 
This change allows the script to skip such tasks.
GEA-709
> Fix failing consolidated report script

- scripts/check-gmp-gos22.04.gmp.py
- scripts/check-gmp-gos24.10.gmp.py
- scripts/monthly-report-gos24.10.gmp.py
- scripts/monthly-report-gos3.gmp.py
- scripts/monthly-report-gos4.gmp.py
The scripts check-gmp.gmp.py and monthly-report.gmp.py hav been renamed
to check-gmp-gos22.04.gmp.py and monthly-report-gos3.gmp.py and the
intended GOS version is added to the help text.
The check-gmp and monthly-report scripts have new 24.10 versions added
which use the new CVSS 3.x and 4.0 severity ratings which splits the
"High" rating into "High" and "Critical".
The renaming makes it more obvious which GOS versions they should be used with.
The new 24.10 versions ensure the scripts can be used with the new GMP/GOS version.
GEA-730
> Add: CVSS3 versions of check-gmp and monthly-report, rename old versions

- .docker/Dockerfile
Avoid GitHub Dockerfile linter warnings in PRs
GitHub lints the Dockerfiles with every PR. Adjust the Dockerfile to get rid of the warnings.
> Avoid GitHub Dockerfile linter warnings in PRs

- .github/workflows/dependency-review.yml
Allow dependency review workflow to add comments to a PR
The workflow requires the pull-request write permission because it wants to add a comment to the current PR.
https://github.com/greenbone/gvm-tools/actions/runs/13108499062/job/36567262284
> Allow dependency review workflow to add comments to a PR

- .github/workflows/ci-python.yml
- .github/workflows/dependency-review.yml
- .github/workflows/deploy-pypi.yml
- .github/workflows/sbom-upload.yml
Always use v3 version of our own Greenbone actions
We want always the latest and greatest without relying on dependabot updates. Try to fix actions/cache issues with gvm-tools.
https://github.com/greenbone/gvm-tools/actions/runs/13759434385/job/38472280308?pr=1195
> Always use v3 version of our own Greenbone actions

- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
Use git-cliff to generate release changelog
git-cliff allows for more flexible release changelog generation.
Add another workflow to show the changelog for all unreleased changes. This allows for checking the changes before making a new release and to decide which release type needs to be applied.
https://jira.greenbone.net/browse/GEA-984
> Use git-cliff to generate release changelog

- .github/workflows/container.yml
Use new container build workflow
Allow for more flexible container image builds. With this change even PRs are build as a container image and can be tested easily.
https://jira.greenbone.net/browse/GEA-1139
> Use new container build workflow
